version: "3"
services:
  app:
    build: .
    command: /bin/bash -c -l "bundle exec rails s -b 0.0.0.0 -p 3000 -e development"
    ports:
     - 3000:3000
    volumes:
     - iris:/usr/local/datalink/iris
  webjs:
    build: .
    command: /bin/bash -c -l "npm install; npm start"
    ports:
     - 8080:8080
    volumes:
     - iris:/usr/local/datalink/iris

volumes:
  iris:
